enabled: true

webhook-url: ""
whitelist: true # Whether to log these commands(whitelist mode) or log everything EXCEPT these commands(false whitelist)
sensitive-commands:
  - "op"
  - "deop"
  - "ban"
  - "ban-ip"
  - "pardon"
  - "pardon-ip"
  - "kick"
  - "stop"
  - "whitelist add"
  - "whitelist remove"
  - "whitelist reload"
  - "give"
  - "stop"
  - "restart"
  - "teleport"
  - "gamemode"
  - "data"