name: SpyCord
version: "1.1a-paper"
main: com.myst1cs04p.spycord.SpyCord
api-version: "1.20"

permissions:
  spycord.version:
    description: "Allows use of the version command."
    default: op
  spycord.reload:
    description: "Allows use of the reload command."
    default: op
  spycord.report:
    description: "Allows use of the report command."
    default: op
  spycord.toggle:
    description: "Allows use of the toggle command."
    default: op
